### ISSUE TITLE
Usage of more than one primer pair

### ISSUE THREAD

**Issue by hoelzer** [willem-stock/CONCOMPRA#1]
Hey, great tool!

I wonder if it is also possible to use more than one primer pair? The example primer FASTA and the description sound like one can only use one primer pair. But what if I sequenced amplicons using more than one primer pair? Can I add more primer sequences to the FASTA file? And if so, how should I name them (`head-1`, `head-2`, ...)

**Comment by willem-stock** [comment]
Hi,
the use of multiple primer pairs in the primer fasta file currently isn't possible. i can suggest two workarounds:
a) if your amplicons have (substantially) different lengths, you can split your data _a priori_ based on length. 
b) You can work sequentially: start with one primer pair in the primer fasta, the reads which fail to map, will be in the 'unmapped' folder. You can rerun CONCOMPRA on those reads with the second primer pair.  
Hope this helps

**Comment by hoelzer** [comment]
Hey, thanks for the suggestions! My amplicons have roughly the same length so I guess I could try the incremental approach b). The challenge will then be to combine the results from the different primer pair runs.
